# Generated by Django 4.0.3 on 2022-04-08 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departaments',
            new_name='Departments',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='DepartamentId',
            new_name='DepartmentId',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='DepartamentName',
            new_name='DepartmentName',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='Departament',
            new_name='Department',
        ),
    ]
