# Generated by Django 4.0.3 on 2022-04-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_rename_departaments_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='DateOfJoining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
